# Generated by Django 4.1.3 on 2022-12-19 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expired_payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pay_user_id', models.IntegerField()),
                ('Penalty_fee_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'Expired_payments',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=100)),
                ('Logo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Payment_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('PaymentDate', models.DateTimeField(auto_now_add=True)),
                ('ExpirationDate', models.DateTimeField(default='')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.services', to_field='Name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payment_user',
            },
        ),
    ]
