# Generated by Django 4.1.3 on 2022-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('user_id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('services', models.CharField(choices=[('NETFLIX', 'Netflix'), ('AMAZON VIDEO', 'Amazon'), ('STAR +', 'Star'), ('PARAMOUNT +', 'Paramount')], max_length=20)),
                ('monto', models.IntegerField(max_length=20)),
            ],
        ),
    ]
