# Generated by Django 4.1.3 on 2022-12-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
